backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
